{% set name = "libtrlib" %}
{% set version = "0.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/felixlen/trlib/archive/refs/tags/{{ version }}.tar.gz
    sha256: 08f778cc5ef4aa3b5e1035b8986c5614adb9d3816fbfabe4b59c605eb8b95bf5

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - libblas
    - liblapack
    - check

test:
  commands:
    - test -f $PREFIX/lib/cmake/trlib/trlib-config.cmake  # [unix]
    - test -f $PREFIX/include/trlib.h  # [unix]
    - test -f $PREFIX/lib/libtrlib${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\trlib\\trlib-config.cmake exit 1  # [win]
    - if not exist %LIBRARY_INC%\\trlib.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\trlib.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\trlib.dll exit 1  # [win]

about:
  home: https://github.com/felixlen/trlib
  license: MIT
  license_file: LICENSE
  summary: Trust Region Subproblem Solver Library

extra:
  feedstock-name: trlib
  recipe-maintainers:
    - traversaro
