{% set name = "ace" %}
{% set version = "6.5.11" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/DOCGroup/ACE_TAO/releases/download/ACE%2BTAO-6_5_11/ACE+TAO-6.5.11.zip
    sha256: ea617bd526cfd3638675912fbcf40d1e34669c33705f356ab035dcaae311f12f

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - vs2017_win-64          # [win64]
    - vs2017_win-32          # [win32]
    - make                   # [not win]
    - perl
  host:
    - openssl
    - zlib
  run:
    - openssl
    - zlib
    
test:
  commands:
    - test -f $PREFIX/lib/libACE.so  # [unix]
    - if not exist %LIBRARY_LIB%\\ACE.lib exit 1  # [win]

about:
  home: https://www.dre.vanderbilt.edu/~schmidt/ACE.html
  license: Other
  license_file: ACE_wrappers/COPYING
  summary: 'The ADAPTIVE Communication Environment'

extra:
  recipe-maintainers:
    - traversaro
