{% set name = "libglvnd" %}
{% set version = "1.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://gitlab.freedesktop.org/glvnd/libglvnd/-/archive/v{{ version }}/libglvnd-v{{ version }}.tar.bz2
    sha256: d0e1925a3c9aee0143b8c181ac31d5637c8faa081759c277b8e16c7075612c11
    patches:
      - libglvnd_look_for_egl_icd_in_system_location.patch

build:
  skip: true  # [not linux]
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - meson
    - pkg-config
    - ninja
  host:
    - xorg-libxext
    - xorg-libx11
    - xorg-xorgproto
    - wayland-protocols

test:
  commands:
    - test -f $PREFIX/lib/libEGL.so.1
    - test -f $PREFIX/lib/libGL.so.1
    - test -f $PREFIX/lib/libGLESv1_CM.so.1
    - test -f $PREFIX/lib/libGLESv2.so.2
    - test -f $PREFIX/lib/libGLX.so.0
    - test -f $PREFIX/lib/libOpenGL.so.0
    - test -f $PREFIX/lib/libGLdispatch.so.0
    - test -f $PREFIX/lib/pkgconfig/egl.pc
    - test -f $PREFIX/lib/pkgconfig/gl.pc
    - test -f $PREFIX/lib/pkgconfig/glesv1_cm.pc
    - test -f $PREFIX/lib/pkgconfig/glesv2.pc
    - test -f $PREFIX/lib/pkgconfig/glx.pc
    - test -f $PREFIX/lib/pkgconfig/opengl.pc
    - test -f $PREFIX/lib/pkgconfig/libglvnd.pc
    - test -f $PREFIX/include/EGL/egl.h
    - test -f $PREFIX/include/EGL/eglext.h
    - test -f $PREFIX/include/EGL/eglplatform.h
    - test -f $PREFIX/include/GL/gl.h
    - test -f $PREFIX/include/GL/glcorearb.h
    - test -f $PREFIX/include/GL/glext.h
    - test -f $PREFIX/include/GL/glx.h
    - test -f $PREFIX/include/GL/glxext.h
    - test -f $PREFIX/include/GLES/egl.h
    - test -f $PREFIX/include/GLES/gl.h
    - test -f $PREFIX/include/GLES/glext.h
    - test -f $PREFIX/include/GLES/glplatform.h
    - test -f $PREFIX/include/GLES2/gl2.h
    - test -f $PREFIX/include/GLES2/gl2ext.h
    - test -f $PREFIX/include/GLES2/gl2platform.h
    - test -f $PREFIX/include/GLES3/gl3.h
    - test -f $PREFIX/include/GLES3/gl31.h
    - test -f $PREFIX/include/GLES3/gl32.h
    - test -f $PREFIX/include/GLES3/gl3ext.h
    - test -f $PREFIX/include/GLES3/gl3platform.h
    - test -f $PREFIX/include/KHR/khrplatform.h
    - test -f $PREFIX/include/glvnd/GLdispatchABI.h
    - test -f $PREFIX/include/glvnd/libeglabi.h
    - test -f $PREFIX/include/glvnd/libglxabi.h

about:
  home: https://gitlab.freedesktop.org/glvnd/libglvnd
  license: LicenseRef-NVIDIA-libglvnd
  license_file: README.md
  summary: GL Vendor-Neutral Dispatch library

extra:
  recipe-maintainers:
    - ehfd
